
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 16 14:55:49 EDT 2016
//----------------------------------------------------

package com;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int TIMES = 4;
  public static final int INPUT = 23;
  public static final int DOUBLE_TYPE = 30;
  public static final int CHARACTER_TYPE = 31;
  public static final int SEMICOLON = 19;
  public static final int PLUS = 2;
  public static final int RBRACE = 17;
  public static final int RPAREN = 15;
  public static final int LOG_OR = 8;
  public static final int LOG_AND = 7;
  public static final int WHILE = 21;
  public static final int BOOLEAN_LITERAL = 28;
  public static final int IDENTIFIER = 33;
  public static final int RETURN = 22;
  public static final int IF = 20;
  public static final int MODULO = 6;
  public static final int LOG_NOT = 9;
  public static final int LPAREN = 14;
  public static final int LBRACE = 16;
  public static final int EQUALS = 10;
  public static final int COMMA = 18;
  public static final int INTEGER_TYPE = 29;
  public static final int EOF = 0;
  public static final int DIVIDE = 5;
  public static final int LESS_THAN = 11;
  public static final int BOOLEAN_TYPE = 32;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int NOT_EQUALS = 13;
  public static final int LESS_THAN_EQUALS = 12;
  public static final int INTEGER_LITERAL = 25;
  public static final int CHARACTER_LITERAL = 27;
  public static final int OUTPUT = 24;
  public static final int DOUBLE_LITERAL = 26;
}

